"""Prometheus metrics tracker for PRSmith v2 KPIs."""

from typing import Optional
from prometheus_client import Counter, Histogram, Gauge

# PR Metrics
PRS_PROCESSED_TOTAL = Counter(
    "prsmith_prs_processed_total",
    "Total number of Pull Requests processed",
    ["status", "repository"],
)

REVIEW_LATENCY_SECONDS = Histogram(
    "prsmith_review_latency_seconds",
    "Time spent running code review in seconds",
    ["repository"],
    buckets=[1, 5, 10, 30, 60, 120, 300, 600],
)

REPAIR_LATENCY_SECONDS = Histogram(
    "prsmith_repair_latency_seconds",
    "Time spent running code repair loop in seconds",
    ["repository", "outcome"],
    buckets=[5, 15, 30, 60, 120, 300, 600, 1200],
)

FINDINGS_TOTAL = Counter(
    "prsmith_findings_total",
    "Total findings identified by reviewer",
    ["severity", "category", "repairability"],
)

FINDINGS_FIXED_TOTAL = Counter(
    "prsmith_findings_fixed_total",
    "Total findings successfully repaired",
    ["category"],
)

FINDINGS_ESCALATED_TOTAL = Counter(
    "prsmith_findings_escalated_total",
    "Total findings escalated to human review",
    ["reason"],
)

REPAIR_ITERATIONS = Histogram(
    "prsmith_repair_iterations",
    "Number of iterations taken to repair an issue",
    ["outcome"],
    buckets=[1, 2, 3, 4, 5, 6, 10],
)

LLM_TOKENS_TOTAL = Counter(
    "prsmith_llm_tokens_total",
    "Total LLM tokens consumed",
    ["model", "type"],  # type: prompt, completion
)

LLM_COST_USD = Counter(
    "prsmith_llm_cost_usd_total",
    "Estimated total LLM cost in USD",
    ["model"],
)

PATCHES_GENERATED_TOTAL = Counter(
    "prsmith_patches_generated_total",
    "Total patches generated by repairer",
)

PATCHES_REJECTED_TOTAL = Counter(
    "prsmith_patches_rejected_total",
    "Total patches rejected by policy or syntax checks",
    ["reason"],
)

VALIDATION_DURATION_SECONDS = Histogram(
    "prsmith_validation_duration_seconds",
    "Time spent executing deterministic validations",
    ["layer", "outcome"],
    buckets=[1, 5, 10, 30, 60, 180, 300],
)

STALE_JOBS_TOTAL = Counter(
    "prsmith_stale_jobs_total",
    "Jobs aborted due to superseded commit SHA",
)

ACTIVE_JOBS = Gauge(
    "prsmith_active_jobs",
    "Number of currently running jobs",
    ["stage"],
)


class MetricsTracker:
    """Convenience helper for recording PRSmith metrics."""

    @staticmethod
    def record_pr_processed(status: str, repository: str) -> None:
        PRS_PROCESSED_TOTAL.labels(status=status, repository=repository).inc()

    @staticmethod
    def record_review_finding(severity: str, category: str, repairability: str) -> None:
        FINDINGS_TOTAL.labels(
            severity=severity, category=category, repairability=repairability
        ).inc()

    @staticmethod
    def record_finding_fixed(category: str) -> None:
        FINDINGS_FIXED_TOTAL.labels(category=category).inc()

    @staticmethod
    def record_finding_escalated(reason: str) -> None:
        FINDINGS_ESCALATED_TOTAL.labels(reason=reason).inc()

    @staticmethod
    def record_llm_usage(model: str, prompt_tokens: int, completion_tokens: int, cost_usd: float) -> None:
        LLM_TOKENS_TOTAL.labels(model=model, type="prompt").inc(prompt_tokens)
        LLM_TOKENS_TOTAL.labels(model=model, type="completion").inc(completion_tokens)
        LLM_COST_USD.labels(model=model).inc(cost_usd)

    @staticmethod
    def record_patch_rejected(reason: str) -> None:
        PATCHES_REJECTED_TOTAL.labels(reason=reason).inc()
