"""add_github_oauth_multi_tenant

Revision ID: 936f4822902d
Revises: 
Create Date: 2026-09-03 15:01:23.117471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '936f4822902d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_embeddings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('commit_sha', sa.String(length=40), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('symbol_name', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('embedding_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_embeddings_commit_sha'), 'code_embeddings', ['commit_sha'], unique=False)
    op.create_index(op.f('ix_code_embeddings_file_path'), 'code_embeddings', ['file_path'], unique=False)
    op.create_index(op.f('ix_code_embeddings_repository_id'), 'code_embeddings', ['repository_id'], unique=False)
    op.create_table('repositories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('github_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('default_branch', sa.String(length=100), nullable=False),
    sa.Column('installation_id', sa.Integer(), nullable=True),
    sa.Column('private', sa.Boolean(), nullable=False),
    sa.Column('last_polled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repositories_full_name'), 'repositories', ['full_name'], unique=True)
    op.create_index(op.f('ix_repositories_github_id'), 'repositories', ['github_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('github_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_github_id'), 'users', ['github_id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('webhook_deliveries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('delivery_id', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('repository_full_name', sa.String(length=255), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_deliveries_delivery_id'), 'webhook_deliveries', ['delivery_id'], unique=True)
    op.create_table('github_connections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=False),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('access_token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('refresh_token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('scopes', sa.String(length=255), nullable=False),
    sa.Column('token_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_github_connections_user_id'), 'github_connections', ['user_id'], unique=True)
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=False),
    sa.Column('pr_title', sa.String(length=512), nullable=False),
    sa.Column('base_sha', sa.String(length=40), nullable=False),
    sa.Column('head_sha', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('triggered_by_user_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_head_sha'), 'jobs', ['head_sha'], unique=False)
    op.create_index(op.f('ix_jobs_pr_number'), 'jobs', ['pr_number'], unique=False)
    op.create_index(op.f('ix_jobs_repository_id'), 'jobs', ['repository_id'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_triggered_by_user_id'), 'jobs', ['triggered_by_user_id'], unique=False)
    op.create_table('repository_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('base_sha', sa.String(length=40), nullable=False),
    sa.Column('head_sha', sa.String(length=40), nullable=False),
    sa.Column('merge_base_sha', sa.String(length=40), nullable=False),
    sa.Column('clone_path', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repository_snapshots_base_sha'), 'repository_snapshots', ['base_sha'], unique=False)
    op.create_index(op.f('ix_repository_snapshots_head_sha'), 'repository_snapshots', ['head_sha'], unique=False)
    op.create_index(op.f('ix_repository_snapshots_repository_id'), 'repository_snapshots', ['repository_id'], unique=False)
    op.create_table('user_repositories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('monitoring_enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_repair_enabled', sa.Boolean(), nullable=False),
    sa.Column('watched_branches', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'repository_id', name='uq_user_repository')
    )
    op.create_index(op.f('ix_user_repositories_repository_id'), 'user_repositories', ['repository_id'], unique=False)
    op.create_index(op.f('ix_user_repositories_user_id'), 'user_repositories', ['user_id'], unique=False)
    op.create_table('artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('artifact_type', sa.String(length=50), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifacts_job_id'), 'artifacts', ['job_id'], unique=False)
    op.create_table('context_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('step_name', sa.String(length=50), nullable=False),
    sa.Column('retrieved_symbols', sa.JSON(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_context_snapshots_job_id'), 'context_snapshots', ['job_id'], unique=False)
    op.create_table('graph_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('snapshot_id', sa.String(length=36), nullable=True),
    sa.Column('commit_sha', sa.String(length=40), nullable=False),
    sa.Column('is_incremental', sa.Boolean(), nullable=False),
    sa.Column('node_count', sa.Integer(), nullable=False),
    sa.Column('edge_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_verified', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['repository_snapshots.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graph_versions_commit_sha'), 'graph_versions', ['commit_sha'], unique=False)
    op.create_index(op.f('ix_graph_versions_repository_id'), 'graph_versions', ['repository_id'], unique=False)
    op.create_table('model_calls',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_calls_job_id'), 'model_calls', ['job_id'], unique=False)
    op.create_table('patches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('diff_content', sa.Text(), nullable=False),
    sa.Column('diff_hash', sa.String(length=64), nullable=False),
    sa.Column('files_changed', sa.JSON(), nullable=False),
    sa.Column('lines_added', sa.Integer(), nullable=False),
    sa.Column('lines_deleted', sa.Integer(), nullable=False),
    sa.Column('is_valid_syntax', sa.Boolean(), nullable=False),
    sa.Column('is_within_scope', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patches_diff_hash'), 'patches', ['diff_hash'], unique=False)
    op.create_index(op.f('ix_patches_job_id'), 'patches', ['job_id'], unique=False)
    op.create_table('repair_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('finding_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('iteration_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repair_runs_job_id'), 'repair_runs', ['job_id'], unique=False)
    op.create_table('review_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('findings_count', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_runs_job_id'), 'review_runs', ['job_id'], unique=False)
    op.create_table('validation_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_runs_job_id'), 'validation_runs', ['job_id'], unique=False)
    op.create_table('graph_nodes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('graph_version_id', sa.String(length=36), nullable=False),
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('node_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('qualified_name', sa.String(length=512), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=True),
    sa.Column('end_line', sa.Integer(), nullable=True),
    sa.Column('source_commit', sa.String(length=40), nullable=False),
    sa.Column('parser_version', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('properties', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['graph_version_id'], ['graph_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graph_nodes_file_path'), 'graph_nodes', ['file_path'], unique=False)
    op.create_index(op.f('ix_graph_nodes_graph_version_id'), 'graph_nodes', ['graph_version_id'], unique=False)
    op.create_index(op.f('ix_graph_nodes_name'), 'graph_nodes', ['name'], unique=False)
    op.create_index(op.f('ix_graph_nodes_node_type'), 'graph_nodes', ['node_type'], unique=False)
    op.create_index(op.f('ix_graph_nodes_qualified_name'), 'graph_nodes', ['qualified_name'], unique=False)
    op.create_index(op.f('ix_graph_nodes_repository_id'), 'graph_nodes', ['repository_id'], unique=False)
    op.create_index(op.f('ix_graph_nodes_source_commit'), 'graph_nodes', ['source_commit'], unique=False)
    op.create_table('repair_iterations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('repair_run_id', sa.String(length=36), nullable=False),
    sa.Column('iteration_number', sa.Integer(), nullable=False),
    sa.Column('patch_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('validation_status', sa.String(length=50), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['repair_run_id'], ['repair_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repair_iterations_repair_run_id'), 'repair_iterations', ['repair_run_id'], unique=False)
    op.create_table('review_findings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('finding_id', sa.String(length=50), nullable=False),
    sa.Column('review_run_id', sa.String(length=36), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('symbol_name', sa.String(length=255), nullable=True),
    sa.Column('start_line', sa.Integer(), nullable=True),
    sa.Column('end_line', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('affected_entities', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('repairability', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['review_run_id'], ['review_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_findings_category'), 'review_findings', ['category'], unique=False)
    op.create_index(op.f('ix_review_findings_finding_id'), 'review_findings', ['finding_id'], unique=False)
    op.create_index(op.f('ix_review_findings_review_run_id'), 'review_findings', ['review_run_id'], unique=False)
    op.create_index(op.f('ix_review_findings_severity'), 'review_findings', ['severity'], unique=False)
    op.create_table('validation_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('validation_run_id', sa.String(length=36), nullable=False),
    sa.Column('layer_name', sa.String(length=50), nullable=False),
    sa.Column('command', sa.String(length=512), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('exit_code', sa.Integer(), nullable=False),
    sa.Column('stdout', sa.Text(), nullable=False),
    sa.Column('stderr', sa.Text(), nullable=False),
    sa.Column('failure_class', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['validation_run_id'], ['validation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_results_validation_run_id'), 'validation_results', ['validation_run_id'], unique=False)
    op.create_table('graph_edges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('graph_version_id', sa.String(length=36), nullable=False),
    sa.Column('source_node_id', sa.String(length=36), nullable=False),
    sa.Column('target_node_id', sa.String(length=36), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('source_commit', sa.String(length=40), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('derived_by', sa.String(length=50), nullable=False),
    sa.Column('properties', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['graph_version_id'], ['graph_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_node_id'], ['graph_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_node_id'], ['graph_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graph_edges_graph_version_id'), 'graph_edges', ['graph_version_id'], unique=False)
    op.create_index(op.f('ix_graph_edges_relationship_type'), 'graph_edges', ['relationship_type'], unique=False)
    op.create_index(op.f('ix_graph_edges_source_node_id'), 'graph_edges', ['source_node_id'], unique=False)
    op.create_index(op.f('ix_graph_edges_target_node_id'), 'graph_edges', ['target_node_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_graph_edges_target_node_id'), table_name='graph_edges')
    op.drop_index(op.f('ix_graph_edges_source_node_id'), table_name='graph_edges')
    op.drop_index(op.f('ix_graph_edges_relationship_type'), table_name='graph_edges')
    op.drop_index(op.f('ix_graph_edges_graph_version_id'), table_name='graph_edges')
    op.drop_table('graph_edges')
    op.drop_index(op.f('ix_validation_results_validation_run_id'), table_name='validation_results')
    op.drop_table('validation_results')
    op.drop_index(op.f('ix_review_findings_severity'), table_name='review_findings')
    op.drop_index(op.f('ix_review_findings_review_run_id'), table_name='review_findings')
    op.drop_index(op.f('ix_review_findings_finding_id'), table_name='review_findings')
    op.drop_index(op.f('ix_review_findings_category'), table_name='review_findings')
    op.drop_table('review_findings')
    op.drop_index(op.f('ix_repair_iterations_repair_run_id'), table_name='repair_iterations')
    op.drop_table('repair_iterations')
    op.drop_index(op.f('ix_graph_nodes_source_commit'), table_name='graph_nodes')
    op.drop_index(op.f('ix_graph_nodes_repository_id'), table_name='graph_nodes')
    op.drop_index(op.f('ix_graph_nodes_qualified_name'), table_name='graph_nodes')
    op.drop_index(op.f('ix_graph_nodes_node_type'), table_name='graph_nodes')
    op.drop_index(op.f('ix_graph_nodes_name'), table_name='graph_nodes')
    op.drop_index(op.f('ix_graph_nodes_graph_version_id'), table_name='graph_nodes')
    op.drop_index(op.f('ix_graph_nodes_file_path'), table_name='graph_nodes')
    op.drop_table('graph_nodes')
    op.drop_index(op.f('ix_validation_runs_job_id'), table_name='validation_runs')
    op.drop_table('validation_runs')
    op.drop_index(op.f('ix_review_runs_job_id'), table_name='review_runs')
    op.drop_table('review_runs')
    op.drop_index(op.f('ix_repair_runs_job_id'), table_name='repair_runs')
    op.drop_table('repair_runs')
    op.drop_index(op.f('ix_patches_job_id'), table_name='patches')
    op.drop_index(op.f('ix_patches_diff_hash'), table_name='patches')
    op.drop_table('patches')
    op.drop_index(op.f('ix_model_calls_job_id'), table_name='model_calls')
    op.drop_table('model_calls')
    op.drop_index(op.f('ix_graph_versions_repository_id'), table_name='graph_versions')
    op.drop_index(op.f('ix_graph_versions_commit_sha'), table_name='graph_versions')
    op.drop_table('graph_versions')
    op.drop_index(op.f('ix_context_snapshots_job_id'), table_name='context_snapshots')
    op.drop_table('context_snapshots')
    op.drop_index(op.f('ix_artifacts_job_id'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index(op.f('ix_user_repositories_user_id'), table_name='user_repositories')
    op.drop_index(op.f('ix_user_repositories_repository_id'), table_name='user_repositories')
    op.drop_table('user_repositories')
    op.drop_index(op.f('ix_repository_snapshots_repository_id'), table_name='repository_snapshots')
    op.drop_index(op.f('ix_repository_snapshots_head_sha'), table_name='repository_snapshots')
    op.drop_index(op.f('ix_repository_snapshots_base_sha'), table_name='repository_snapshots')
    op.drop_table('repository_snapshots')
    op.drop_index(op.f('ix_jobs_triggered_by_user_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_repository_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_pr_number'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_head_sha'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_github_connections_user_id'), table_name='github_connections')
    op.drop_table('github_connections')
    op.drop_index(op.f('ix_webhook_deliveries_delivery_id'), table_name='webhook_deliveries')
    op.drop_table('webhook_deliveries')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_github_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_repositories_github_id'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_full_name'), table_name='repositories')
    op.drop_table('repositories')
    op.drop_index(op.f('ix_code_embeddings_repository_id'), table_name='code_embeddings')
    op.drop_index(op.f('ix_code_embeddings_file_path'), table_name='code_embeddings')
    op.drop_index(op.f('ix_code_embeddings_commit_sha'), table_name='code_embeddings')
    op.drop_table('code_embeddings')
    # ### end Alembic commands ###
