"""hardening_pass_v2_models

Revision ID: 9f08858b0178
Revises: 936f4822902d
Create Date: 2026-09-04 06:57:24.922441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f08858b0178'
down_revision = '936f4822902d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('code_embeddings', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_code_embeddings_graph_version_id', 'graph_versions', ['graph_version_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('graph_edges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edge_provenance', sa.String(length=50), nullable=False, server_default='DIRECT_STATIC'))
        batch_op.add_column(sa.Column('provenance_weight', sa.Float(), nullable=False, server_default='1.0'))
        batch_op.create_index(batch_op.f('ix_graph_edges_edge_provenance'), ['edge_provenance'], unique=False)

    with op.batch_alter_table('graph_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('graph_content_hash', sa.String(length=64), nullable=False, server_default=''))
        batch_op.create_index(batch_op.f('ix_graph_versions_graph_content_hash'), ['graph_content_hash'], unique=False)

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('worker_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('lease_until', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('graph_version_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('snapshot_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('superseded_by_job_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_jobs_graph_version_id'), ['graph_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_snapshot_id'), ['snapshot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_superseded_by_job_id'), ['superseded_by_job_id'], unique=False)
        batch_op.create_foreign_key('fk_jobs_snapshot_id', 'repository_snapshots', ['snapshot_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_jobs_superseded_by_job_id', 'jobs', ['superseded_by_job_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_jobs_graph_version_id', 'graph_versions', ['graph_version_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('patches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artifact_hash', sa.String(length=64), nullable=False, server_default=''))
        batch_op.create_index(batch_op.f('ix_patches_artifact_hash'), ['artifact_hash'], unique=False)

    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('github_installation_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_repositories_github_installation_id'), ['github_installation_id'], unique=False)
        batch_op.create_foreign_key('fk_repositories_github_installation_id', 'github_installations', ['github_installation_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('review_findings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_hash', sa.String(length=64), nullable=False, server_default=''))
        batch_op.create_index(batch_op.f('ix_review_findings_content_hash'), ['content_hash'], unique=False)

    with op.batch_alter_table('review_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('head_sha', sa.String(length=40), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('evidence_validation_passed', sa.Boolean(), nullable=False, server_default='1'))
        batch_op.create_index(batch_op.f('ix_review_runs_head_sha'), ['head_sha'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_version', sa.Integer(), nullable=False, server_default='1'))

    with op.batch_alter_table('validation_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('head_sha', sa.String(length=40), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('patch_artifact_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('result_hash', sa.String(length=64), nullable=False, server_default=''))
        batch_op.create_index(batch_op.f('ix_validation_runs_head_sha'), ['head_sha'], unique=False)
        batch_op.create_index(batch_op.f('ix_validation_runs_patch_artifact_hash'), ['patch_artifact_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_validation_runs_result_hash'), ['result_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('validation_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_validation_runs_result_hash'))
        batch_op.drop_index(batch_op.f('ix_validation_runs_patch_artifact_hash'))
        batch_op.drop_index(batch_op.f('ix_validation_runs_head_sha'))
        batch_op.drop_column('result_hash')
        batch_op.drop_column('patch_artifact_hash')
        batch_op.drop_column('head_sha')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('session_version')

    with op.batch_alter_table('review_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_runs_head_sha'))
        batch_op.drop_column('evidence_validation_passed')
        batch_op.drop_column('head_sha')

    with op.batch_alter_table('review_findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_findings_content_hash'))
        batch_op.drop_column('content_hash')

    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.drop_constraint('fk_repositories_github_installation_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_repositories_github_installation_id'))
        batch_op.drop_column('github_installation_id')

    with op.batch_alter_table('patches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patches_artifact_hash'))
        batch_op.drop_column('artifact_hash')

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_jobs_graph_version_id', type_='foreignkey')
        batch_op.drop_constraint('fk_jobs_superseded_by_job_id', type_='foreignkey')
        batch_op.drop_constraint('fk_jobs_snapshot_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_jobs_superseded_by_job_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_graph_version_id'))
        batch_op.drop_column('superseded_by_job_id')
        batch_op.drop_column('snapshot_id')
        batch_op.drop_column('graph_version_id')
        batch_op.drop_column('lease_until')
        batch_op.drop_column('worker_id')
        batch_op.drop_column('version')

    with op.batch_alter_table('graph_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_graph_versions_graph_content_hash'))
        batch_op.drop_column('graph_content_hash')

    with op.batch_alter_table('graph_edges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_graph_edges_edge_provenance'))
        batch_op.drop_column('provenance_weight')
        batch_op.drop_column('edge_provenance')

    with op.batch_alter_table('code_embeddings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_code_embeddings_graph_version_id', type_='foreignkey')

    # ### end Alembic commands ###
